# Generated by Django 5.0.4 on 2024-04-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plates',
            name='plate',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
