# Generated by Django 5.0.4 on 2024-04-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_plates_plate_alter_plates_user_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
