# Generated by Django 5.0.4 on 2024-04-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_plates_plate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingRate',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='amount',
            new_name='balance',
        ),
    ]
