# Generated by Django 5.0.4 on 2024-04-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blacklistedvehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedVehicle',
        ),
    ]
