# Generated by Django 5.0.4 on 2024-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_balance_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='sessions',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
