# Generated by Django 5.0.4 on 2024-04-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='plate',
        ),
        migrations.DeleteModel(
            name='Plates',
        ),
        migrations.DeleteModel(
            name='Sessions',
        ),
    ]
